# app/config/security.yml
jms_security_extra:
      secure_all_services: false
      expressions: true
security:

    encoders:
        AdrianG\RegisterBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        our_db_provider:
            entity:
                class: AdrianGRegisterBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            provider: our_db_provider


        default:
            pattern: ^/
            form_login:
              login_path: /login
              check_path: /login_check
              default_target_path: /
            logout:
              path: /logout
              target: /
            anonymous: true



    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/user/admin, roles: ROLE_ADMIN }
        - { path: /login$, access: "!isAuthenticated()" }
        - { path: /user/register$, access: "!isAuthenticated()" }
        - { path: ^/multimedia/search, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/multimedia/upload, access: "isAuthenticated()" }
        - { path: ^/multimedia/galleryAcess, access: "isAuthenticated()" }
        - { path: ^/multimedia/createGallery, access: "isAuthenticated()" }
        - { path: ^/multimedia/delete, access: "isAuthenticated()" }
