<?php

namespace AdrianG\RegisterBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class LoginController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AdrianG\RegisterBundle\Controller\LoginController();
        return $instance;
    }
}
