<?php

namespace multimediaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MyGalleriesController__JMSInjector
{
    public static function inject($container) {
        $instance = new \multimediaBundle\Controller\MyGalleriesController();
        return $instance;
    }
}
