multimedia_homepage:
    path:     /
    defaults: { _controller: multimediaBundle:Default:index }

multimedia_upload:
    path:     /upload
    defaults: { _controller: multimediaBundle:Upload:index }
